Export liblocal_planner.so for other projects (#402)
This patch introduces a minor change to local_planner's CMakeLists.txt,
which allows other cmake projects to use the library as an external
project. Without this change, compiling against local_planner introduces
the following errors (to begin with):

undefined reference to `avoidance::LocalPlanner::LocalPlanner()'
undefined reference to `avoidance::LocalPlanner::~LocalPlanner()'